name: Ansible Lint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and Ansible-Lint via pip
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint community.general

      - name: Run Ansible Lint
        run: |
          ansible-lint playbook.yml
